### PR TITLE
Ubuntu 20.04

### PR DESCRIPTION
**Pull request by michaelweiser**
Adjust the installer for Ubuntu 20.04.

### CODE REVIEW

**Comment by Jack28** [comment]
Out of curiosity I opened a pull request on your pull request but it doesn't show up here
https://github.com/michaelweiser/PeekabooAV-Installer/pull/1

**Comment by michaelweiser** [comment]
> Out of curiosity I opened a pull request on your pull request but it doesn't show up here
> [michaelweiser#1](https://github.com/michaelweiser/PeekabooAV-Installer/pull/1)
> 
> Otherwise LGTM

Heh, yeah, it's become a pull request against my branch so is shown in my fork.

To the matter at hand: Do we wanna push the recommended version already? I just wanted to provide the option to ease testing (and because I had to reinstall my development machine anyway and wanted to go bleeding edge FWIW ;).

I'm still uncovering bugs in Peekaboo with the more recent python 3.8 (luckily only in the test suite so far). Cuckoo is likely broken on 20.04. So I'd recommend holding off on changing the recommendation to 20.04 until at least we can offer Cortex/CAPEv2 as a functioning alternative to Cuckoo.

Or we enhance machine role separation to separate machines and make Cuckoo at least optional in the installer so it can live on its own 18.04 machine. Or the installer, through the power of ansible, installs the system to multiple machines. I'm wondering if all this is worthwhile effort though, with everything becoming a container nowadays. I'd postpone all of them to a separate PR anyways.

**Comment by Jack28** [comment]
For the installation I set up this morning I quickly changed the inventory file to only include peekaboo.
I agree it wouldn't make sense to implement, test, workaround ... no harm done keeping this pull request for later in the process/transition.

**Comment by michaelweiser** [comment]
Good stuff. If that worked, role separation seems to be quite good for Cuckoo already without ever having been tested.

**Comment by michaelweiser** [comment]
Just reran vagrant with 18.04 and 20.04 without problems. Merging now.

**Pull request merged**
